### ISSUE TITLE
Ensure state of Nginx site config file - fatal: [dev1]: FAILED! 

### ISSUE THREAD

**Issue by telezoic** [dpla/automation#168]
Hi folks, 

I'm starting with a new, fresh build of the automation repo. After I run: 

`ansible-playbook -i ingestion -u daniel dev_ingestion_all.yml --extra-vars "initial_run=true"`

 I'm getting the following error:

`TASK [site_proxy : Ensure state of Nginx site config file] *********************
fatal: [dev1]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: ERROR! 'dict object' has no attribute 'thumbp'"}`

I've tried reloading/provisioning vagrant to no avail. I'm not sure where/how I could correct this and was hoping you might have some advice. 

Thanks, 
Dan

**Comment by markbreedlove** [comment]
Hello, Daniel,

There's a pull request currently open (https://github.com/dpla/automation/pull/164) that should fix this:

https://github.com/dpla/automation/commit/979bc18e66d2d019c7e3033d35b6b63bc93231e2#diff-1b32916f3fdc56c4d29693b69ca9645e

I neglected to add an inventory group `thumbp` to the `ingestion` inventory in an earlier update that was pushed through quickly for DPLAfest. (It had been added to the `development` inventory.) The pull request should be merged soon and then this should be fixed in version 3.0. The only trick is that the version 3.0 upgrade will require a few simple steps on your part, which will be documented in the READMEs.

If you want to keep moving in the meantime, you can modify your `ingestion` inventory file to include the following lines, and revert the change before pulling from the repository again.
```
[thumbp]
dev1
```

**Comment by markbreedlove** [comment]
On second thought, I can make a maintenance branch for version 2 and add those lines to the inventory file.

**Comment by markbreedlove** [comment]
This should be OK now in https://github.com/dpla/automation/releases/tag/v2.11.1 as well as `develop` and `master`.

**Comment by telezoic** [comment]
Right on. 
I'm going to pull this now. 
Thanks!
